### ISSUE TITLE
OMPython 3.3 error

### ISSUE THREAD

**Issue by valfaro** [OpenModelica/OMPython#149]
After update Python from 3.8.8 to 3.9.8 -- Error: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren' at _imit_.py line 962.

**Comment by valfaro** [comment]
OMPython works with Python v3.8.9 but not with v3.9.1 and up.

**Comment by casella** [comment]
@valfaro, why did you close this? Looks like a serious issue...

**Comment by arun3688** [comment]
@casella It is due to `deprecated function` from the package provider the issue is already fixed with this commit https://github.com/OpenModelica/OMPython/commit/59ef1e3ea25ccc5b60496622b0415df36316d3c0

@valfaro  We are not using the `getChildren()` method anymore,  you are using older version of OMPython please update your OMPython package . `pip install OMPython -U` and this should work

**Comment by casella** [comment]
@valfaro please comment here if things are still broken after the latest fixes.

**Comment by valfaro** [comment]
pip install OMPython -U dosen´t fix the issue.  You need to clone the master and install OMPython from the local zip file.  Software version must be updated.

**Comment by arun3688** [comment]
@valfaro can you uninstall the package and do a pip install again

**Comment by valfaro** [comment]
It was one of the several procedures I try.
pip normally install OMPython register as v3.3.0 (but with old files) that can not be "updated" because master version is also 3.3.0.
Please note that last release at GitHub is v3.2.0
Probably publishing a "new" release (3.3.1 ?) the update via pip will work.
